stages:
  - Build

build app:
  stage: Build
  image: docker:19.03.1
  services:
  - docker:19.03.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build . --cache-from $CI_REGISTRY_IMAGE:latest
                    -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
                    -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
                    -t $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:latest
